theme = "gruvbox"

[editor]
scrolloff = 10
middle-click-paste = true
scroll-lines = 1
line-number = "relative"
cursorline = true
idle-timeout = 1
completion-timeout = 1
completion-trigger-len = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

# Goto mode shortcuts
[keys.normal.g]
"d" = "goto_line_start"
"n" = "goto_line_end"
"l" = "goto_definition"
[keys.select.g]
"d" = "goto_line_start"
"n" = "goto_line_end"
"l" = "goto_definition"

# Window mode shortcut
[keys.normal.C-w]
"d" = "jump_view_left"
"h" = "jump_view_down"
"t" = "jump_view_up"
"n" = "jump_view_right"
"D" = "swap_view_left"
"H" = "swap_view_down"
"T" = "swap_view_up"
"N" = "swap_view_right"


[editor.soft-wrap]
enable = true

[keys.normal]
"d" = "move_char_left"
"n" = "move_char_right"
"h" = "move_line_down"
"t" = "move_line_up"

"e" = "delete_selection"
# Run yazi
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"

[keys.select]
"d" = "extend_char_left"
"n" = "extend_char_right"
"h" = "extend_line_down"
"t" = "extend_line_up"

"e" = "delete_selection"

