[[language]]
name = "ocaml"
auto-format = true

[[language]]
name = "ocaml-interface"
auto-format = true

[[language]]
name = "markdown"
roots = []
scope = "source.md"
file-types = ["md"]
language-servers = [ "ltex-ls" ]
formatter = { command = "npx", args = [ "prettier", "--parser", "markdown", "--prose-wrap", "always" ]}
auto-format = true

[language-server.ltex-ls]
command = "ltex-ls"
config = { tex = { ltex-ls = { path = "/home/scrabsha/.local/ltex/" } } }

[language-server.ocamllsp]
command = "ocamllsp"

[[language]]
name = "rust"
language-servers = [
    "rust-analyzer",
]

[language-server.rust-analyzer.config]
rust-analyzer.cargo.autoreload = true
rust-analyzer.cargo.sysroot = "discover"
rust-analyzer.rustc.source = "discover"
rust-analyzer.check.command = "clippy"
rust-analyzer.rustfmt.rangeFormatting.enable = true
rust-analyzer.lru.capacity = 1024
